# Generated by Django 3.0.5 on 2020-04-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='email',
        ),
        migrations.RemoveField(
            model_name='email',
            name='password',
        ),
    ]
